// This file is automatically generated, it should not be edited directly.
import 'package:firebase_core/firebase_core.dart';

const FirebaseOptions firebaseOptions = FirebaseOptions(
  apiKey: "AIzaSyAhqcxWMTWCyUVWvY4Jloc0EzddJDjeO4U",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "atya-e23c9",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
);
